### ISSUE TITLE
EXPLAIN PLEASE !!!

### ISSUE THREAD

**Issue by n0problem404** [Varanida/varanida-extension#10]
I and  many of my freands install your extension. All of us save on paper our password and passphrase. And today i and other try to unlock our profile but what we see ? Hm ? How you think ?
All our passwords writed like "wrong password" and then we tried use our passphrase but we create with 6 words and now extension say need 12 words. Its looks like scam. Please explain this!

**Comment by mcrozes** [comment]
Hello -

Support is provided on our Zendesk portal, please contact us directly https://varanida.zendesk.com/hc/en-us/requests/new for help and assistance.

--

I think you refer to your seedphrase. Your seedphrase is personal and is a list of 12 words (not 6). Most likely you did not copy the entire phrase, explaining why you can't retrieve your wallet after a reinstall. Losing your seedphrase is like losing your password, meaning we (as admin) don't have the ability to retrieve your information as we don't know what your password is.

To mitigate this issue, we will make some slight changes on the UI to allow users to download their credentials directly on their computer and increase the size of the area displaying the passphrase to show the entire seed (12 words)

I will go ahead and close this issue, if you need further assistance, please contact us directly using this link: https://varanida.zendesk.com/hc/en-us/requests/new

**Comment by n0problem404** [comment]
Well i just create new account and looks better when i write seedphrase. Thanks for changes, but what with people who didnt know about it and do mistake like me ?
