### ISSUE TITLE
Limit number of digit when checking VAD balance

### ISSUE THREAD

**Issue by mcrozes** [Varanida/varanida-extension#2]
`307.59000000000003 VAD` limit to 3 or 4 digits

**Comment by silto** [comment]
fixed in commit [c845cdd76124c3222f4cea2d7deb644e39576bdf](https://github.com/Varanida/varanida-extension/commit/c845cdd76124c3222f4cea2d7deb644e39576bdf)
floored to 1/100th (since we reward 0.01 at a time anything more precise is useless)
